# Generated by Django 3.1.4 on 2021-01-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My株site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
        ),
    ]
