# Generated by Django 3.1.4 on 2021-02-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My株site', '0003_favorite_code_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=10)),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
    ]
