# Generated by Django 3.1.4 on 2021-03-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My株site', '0005_imagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmodel',
            name='images',
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='images_code',
            field=models.CharField(default=7, max_length=10),
            preserve_default=False,
        ),
    ]
